name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Install Dependencies
        run: ~/.local/bin/uv pip install -e .[dev]

      - name: Lint with flake8
        run: ~/.local/bin/uv run flake8 src

      - name: Test with pytest
        run: ~/.local/bin/uv run pytest

      - name: Type check with mypy
        run: ~/.local/bin/uv run mypy src

      - name: Security check with bandit
        run: ~/.local/bin/uv run bandit -r src